import pandas as pd
import glob
import os

def find_latest_file():
    """Finds the most recent CSV file generated by the fetcher."""
    list_of_files = glob.glob('bse_announcements_*.csv') 
    if not list_of_files:
        return None
    return max(list_of_files, key=os.path.getctime)

def categorize_updates():
    csv_file = find_latest_file()
    if not csv_file:
        print("No data file found. Run 'fetch_bse_feed.py' first.")
        return

    print(f"Processing file: {csv_file}")
    try:
        df = pd.read_csv(csv_file)
    except pd.errors.EmptyDataError:
        print("File is empty.")
        return

    if df.empty:
        print("DataFrame is empty.")
        return

    # Define Keywords for Categories
    # This dictionary maps a Category Name to a list of Keywords
    categories = {
        "Financial_Results": ['Result', 'Financial', 'Quarterly', 'Audited', 'Unaudited'],
        "Dividends": ['Dividend', 'Interim Dividend', 'Final Dividend'],
        "Corporate_Actions": ['Bonus', 'Split', 'Rights Issue', 'Buyback'],
        "Board_Meetings": ['Board Meeting', 'Consider', 'Approve'],
        "Business_Updates": ['Order', 'Bagged', 'Awarded', 'Acquisition', 'MoU', 'Agreement', 'Contract'],
        "Governance": ['Resignation', 'Appointment', 'Cessation'],
        "Credit_Ratings": ['Rating', 'Credit Rating', 'Downgrade', 'Upgrade']
    }

    print(f"\n--- DAILY DIGEST: {len(df)} Total Announcements ---")

    summary_dfs = {}

    for cat_name, keywords in categories.items():
        # Create a regex pattern from keywords (case insensitive)
        pattern = '|'.join(keywords)
        
        # Filter: Check both 'Subject' and 'Category' columns for the keywords
        mask = (
            df['Subject'].str.contains(pattern, case=False, na=False) | 
            df['Category'].str.contains(pattern, case=False, na=False)
        )
        filtered_df = df[mask]
        
        summary_dfs[cat_name] = filtered_df
        
        # Print Stats
        if not filtered_df.empty:
            print(f"  > {cat_name.replace('_', ' ')}: {len(filtered_df)}")
            
            # Save individual CSVs for key categories for easy access
            if cat_name in ["Financial_Results", "Dividends", "Corporate_Actions", "Business_Updates"]:
                output_file = f"filtered_{cat_name.lower()}.csv"
                filtered_df.to_csv(output_file, index=False)

    # --- PREVIEWS ---
    # Show a quick sneak peek of high-value information
    
    if not summary_dfs['Dividends'].empty:
        print("\n--- Upcoming Dividends (Preview) ---")
        print(summary_dfs['Dividends'][['Stock_Name', 'Subject']].head(3).to_string(index=False))

    if not summary_dfs['Corporate_Actions'].empty:
        print("\n--- Splits / Bonus / Buybacks (Preview) ---")
        print(summary_dfs['Corporate_Actions'][['Stock_Name', 'Subject']].head(3).to_string(index=False))
        
    if not summary_dfs['Business_Updates'].empty:
        print("\n--- Major Business Updates (Preview) ---")
        print(summary_dfs['Business_Updates'][['Stock_Name', 'Subject']].head(3).to_string(index=False))

    print(f"\nDetailed CSVs have been saved (e.g., filtered_results.csv, filtered_dividends.csv)")

if __name__ == "__main__":
    categorize_updates()